"""empty message

Revision ID: 798420f2b15e
Revises: 
Create Date: 2018-09-18 09:23:45.301746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '798420f2b15e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coffees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coffee_name', sa.String(length=64), nullable=False),
    sa.Column('coffee_img', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stu_name', sa.String(length=32), nullable=False),
    sa.Column('stu_num', sa.String(length=8), nullable=False),
    sa.Column('stu_sex', sa.Boolean(), nullable=True),
    sa.Column('stu_age', sa.SmallInteger(), nullable=True),
    sa.Column('hobby', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('avatar', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('students')
    op.drop_table('coffees')
    # ### end Alembic commands ###
